### ISSUE TITLE
Unconditional use of sys/sysinfo.h header file

### ISSUE THREAD

**Issue by paspro** [code-saturne/code_saturne#141]
File `src/alge/cs_sles_mumps.cpp` includes the `<sys/sysinfo.h>` header file and utilises it although this is not available on all platforms e.g. macOS.

**Comment by JeromeBonelle** [comment]
Thank you for this feedback. Here is a patch that should solve the problem.

**Comment by JeromeBonelle** [comment]
I don't succeed adding a patch...

**Comment by JeromeBonelle** [comment]
A fix has been pushed into the EDF's internal Gitlab repository (a synchronization with the GitHub mirror has to be performed now).

**Comment by JeromeBonelle** [comment]
This should be fix thanks to commit 6e2797cee10072891c24b3caa6dd673aeda3f727

**Comment by paspro** [comment]
Another error remains:

../../../src/alge/cs_sles_mumps.cpp: In function 'void _automatic_smumps_settings_before_facto(const cs_param_sles_t*, SMUMPS_STRUC_C*)':
../../../src/alge/cs_sles_mumps.cpp:2581:21: error: aggregate '_automatic_smumps_settings_before_facto(const cs_param_sles_t*, SMUMPS_STRUC_C*)::sysinfo sys' has incomplete type and cannot be defined
 2581 |     struct sysinfo  sys;
      |                     ^~~
../../../src/alge/cs_sles_mumps.cpp:2582:33: error: invalid use of incomplete type 'struct _automatic_smumps_settings_before_facto(const cs_param_sles_t*, SMUMPS_STRUC_C*)::sysinfo'
 2582 |     short  status = sysinfo(&sys);
      |                                 ^
.

**Comment by JeromeBonelle** [comment]
A complement has been pushed in the Gitlab. You will see the fix after the next synchronization.
